services:
  frontend:
      build: ./Client
      ports:
        - "5173:5173"
      restart: unless-stopped
  backend:
      build: ./Server
      network_mode: host
      ports:
        - "3000:3000"
      restart: unless-stopped
