networks:
  appnet:
    driver: bridge

services:
  frontend:
    build: ./Client
    ports:
      - 5173:5173
    networks:
      - appnet
    restart: unless-stopped
  backend:
    build: ./Server
    ports:
      - 3000:3000
    networks:
      - appnet
    restart: unless-stopped
  cloudpub:
    image: cloudpub/cloudpub:latest
    restart: unless-stopped
    environment:
      - TOKEN=CLOUDPUB_TOKEN
      - HTTP=frontend:5173,backend:3000
    command: run
    depends_on:
      - frontend
      - backend
    volumes:
      - cloudpub-config:/home/cloudpub
    networks:
      - appnet

volumes:
  cloudpub-config:
